/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as HealthRouteImport } from './../routes/health'
import { Route as AuthenticatedRouteRouteImport } from './../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as ShowcaseOrganismsRouteImport } from './../routes/showcase/organisms'
import { Route as AuthenticatedDashboardRouteImport } from './../routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosIndexRouteImport } from './../routes/_authenticated/contratos/index'
import { Route as AuthenticatedContratosCriarRouteImport } from './../routes/_authenticated/contratos/criar'
import { Route as AuthenticatedContratosIdRouteImport } from './../routes/_authenticated/contratos/$id'
import { Route as AuthenticatedParceirosTerritoriosIndexRouteImport } from './../routes/_authenticated/parceiros/territorios/index'
import { Route as AuthenticatedParceirosFornecedoresIndexRouteImport } from './../routes/_authenticated/parceiros/fornecedores/index'
import { Route as AuthenticatedParceirosFinanciadoresIndexRouteImport } from './../routes/_authenticated/parceiros/financiadores/index'
import { Route as AuthenticatedParceirosColaboradoresIndexRouteImport } from './../routes/_authenticated/parceiros/colaboradores/index'
import { Route as AuthenticatedParceirosAtosIndexRouteImport } from './../routes/_authenticated/parceiros/atos/index'
import { Route as AuthenticatedParceirosFornecedoresCriarRouteImport } from './../routes/_authenticated/parceiros/fornecedores/criar'
import { Route as AuthenticatedParceirosFornecedoresIdRouteImport } from './../routes/_authenticated/parceiros/fornecedores/$id'
import { Route as AuthenticatedParceirosFinanciadoresCriarRouteImport } from './../routes/_authenticated/parceiros/financiadores/criar'
import { Route as AuthenticatedParceirosFinanciadoresIdRouteImport } from './../routes/_authenticated/parceiros/financiadores/$id'
import { Route as AuthenticatedParceirosAtosCriarRouteImport } from './../routes/_authenticated/parceiros/atos/criar'
import { Route as AuthenticatedParceirosAtosIdRouteImport } from './../routes/_authenticated/parceiros/atos/$id'
import { Route as AuthenticatedContratosAditivoIdRouteImport } from './../routes/_authenticated/contratos/aditivo.$id'
import { Route as AuthenticatedContratosIdEditarRouteImport } from './../routes/_authenticated/contratos/$id.editar'
import { Route as AuthenticatedParceirosFornecedoresIdEditarRouteImport } from './../routes/_authenticated/parceiros/fornecedores/$id.editar'
import { Route as AuthenticatedParceirosFinanciadoresIdEditarRouteImport } from './../routes/_authenticated/parceiros/financiadores/$id.editar'
import { Route as AuthenticatedParceirosAtosIdEditarRouteImport } from './../routes/_authenticated/parceiros/atos/$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseOrganismsRoute = ShowcaseOrganismsRouteImport.update({
  id: '/showcase/organisms',
  path: '/showcase/organisms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosCriarRoute =
  AuthenticatedContratosCriarRouteImport.update({
    id: '/contratos/criar',
    path: '/contratos/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosTerritoriosIndexRoute =
  AuthenticatedParceirosTerritoriosIndexRouteImport.update({
    id: '/parceiros/territorios/',
    path: '/parceiros/territorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIndexRoute =
  AuthenticatedParceirosFornecedoresIndexRouteImport.update({
    id: '/parceiros/fornecedores/',
    path: '/parceiros/fornecedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIndexRoute =
  AuthenticatedParceirosFinanciadoresIndexRouteImport.update({
    id: '/parceiros/financiadores/',
    path: '/parceiros/financiadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosColaboradoresIndexRoute =
  AuthenticatedParceirosColaboradoresIndexRouteImport.update({
    id: '/parceiros/colaboradores/',
    path: '/parceiros/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosIndexRoute =
  AuthenticatedParceirosAtosIndexRouteImport.update({
    id: '/parceiros/atos/',
    path: '/parceiros/atos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFornecedoresCriarRoute =
  AuthenticatedParceirosFornecedoresCriarRouteImport.update({
    id: '/parceiros/fornecedores/criar',
    path: '/parceiros/fornecedores/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIdRoute =
  AuthenticatedParceirosFornecedoresIdRouteImport.update({
    id: '/parceiros/fornecedores/$id',
    path: '/parceiros/fornecedores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresCriarRoute =
  AuthenticatedParceirosFinanciadoresCriarRouteImport.update({
    id: '/parceiros/financiadores/criar',
    path: '/parceiros/financiadores/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIdRoute =
  AuthenticatedParceirosFinanciadoresIdRouteImport.update({
    id: '/parceiros/financiadores/$id',
    path: '/parceiros/financiadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosCriarRoute =
  AuthenticatedParceirosAtosCriarRouteImport.update({
    id: '/parceiros/atos/criar',
    path: '/parceiros/atos/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosIdRoute =
  AuthenticatedParceirosAtosIdRouteImport.update({
    id: '/parceiros/atos/$id',
    path: '/parceiros/atos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosAditivoIdRoute =
  AuthenticatedContratosAditivoIdRouteImport.update({
    id: '/contratos/aditivo/$id',
    path: '/contratos/aditivo/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdEditarRoute =
  AuthenticatedContratosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedContratosIdRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIdEditarRoute =
  AuthenticatedParceirosFornecedoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosFornecedoresIdRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIdEditarRoute =
  AuthenticatedParceirosFinanciadoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosFinanciadoresIdRoute,
  } as any)
const AuthenticatedParceirosAtosIdEditarRoute =
  AuthenticatedParceirosAtosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosAtosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/parceiros/atos/': typeof AuthenticatedParceirosAtosIndexRoute
  '/parceiros/colaboradores/': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/parceiros/financiadores/': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/parceiros/fornecedores/': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/parceiros/territorios/': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/parceiros/atos': typeof AuthenticatedParceirosAtosIndexRoute
  '/parceiros/colaboradores': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/parceiros/financiadores': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/parceiros/fornecedores': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/parceiros/territorios': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/_authenticated/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/_authenticated/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/_authenticated/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/_authenticated/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/_authenticated/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/_authenticated/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/_authenticated/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/_authenticated/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/_authenticated/parceiros/atos/': typeof AuthenticatedParceirosAtosIndexRoute
  '/_authenticated/parceiros/colaboradores/': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/_authenticated/parceiros/financiadores/': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/_authenticated/parceiros/fornecedores/': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/_authenticated/parceiros/territorios/': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/_authenticated/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/_authenticated/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/_authenticated/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/dashboard'
    | '/showcase/organisms'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/contratos/'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
    | '/parceiros/atos/$id'
    | '/parceiros/atos/criar'
    | '/parceiros/financiadores/$id'
    | '/parceiros/financiadores/criar'
    | '/parceiros/fornecedores/$id'
    | '/parceiros/fornecedores/criar'
    | '/parceiros/atos/'
    | '/parceiros/colaboradores/'
    | '/parceiros/financiadores/'
    | '/parceiros/fornecedores/'
    | '/parceiros/territorios/'
    | '/parceiros/atos/$id/editar'
    | '/parceiros/financiadores/$id/editar'
    | '/parceiros/fornecedores/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/dashboard'
    | '/showcase/organisms'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/contratos'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
    | '/parceiros/atos/$id'
    | '/parceiros/atos/criar'
    | '/parceiros/financiadores/$id'
    | '/parceiros/financiadores/criar'
    | '/parceiros/fornecedores/$id'
    | '/parceiros/fornecedores/criar'
    | '/parceiros/atos'
    | '/parceiros/colaboradores'
    | '/parceiros/financiadores'
    | '/parceiros/fornecedores'
    | '/parceiros/territorios'
    | '/parceiros/atos/$id/editar'
    | '/parceiros/financiadores/$id/editar'
    | '/parceiros/fornecedores/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/_authenticated/dashboard'
    | '/showcase/organisms'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/criar'
    | '/_authenticated/contratos/'
    | '/_authenticated/contratos/$id/editar'
    | '/_authenticated/contratos/aditivo/$id'
    | '/_authenticated/parceiros/atos/$id'
    | '/_authenticated/parceiros/atos/criar'
    | '/_authenticated/parceiros/financiadores/$id'
    | '/_authenticated/parceiros/financiadores/criar'
    | '/_authenticated/parceiros/fornecedores/$id'
    | '/_authenticated/parceiros/fornecedores/criar'
    | '/_authenticated/parceiros/atos/'
    | '/_authenticated/parceiros/colaboradores/'
    | '/_authenticated/parceiros/financiadores/'
    | '/_authenticated/parceiros/fornecedores/'
    | '/_authenticated/parceiros/territorios/'
    | '/_authenticated/parceiros/atos/$id/editar'
    | '/_authenticated/parceiros/financiadores/$id/editar'
    | '/_authenticated/parceiros/fornecedores/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ShowcaseOrganismsRoute: typeof ShowcaseOrganismsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/organisms': {
      id: '/showcase/organisms'
      path: '/showcase/organisms'
      fullPath: '/showcase/organisms'
      preLoaderRoute: typeof ShowcaseOrganismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/criar': {
      id: '/_authenticated/contratos/criar'
      path: '/contratos/criar'
      fullPath: '/contratos/criar'
      preLoaderRoute: typeof AuthenticatedContratosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/territorios/': {
      id: '/_authenticated/parceiros/territorios/'
      path: '/parceiros/territorios'
      fullPath: '/parceiros/territorios/'
      preLoaderRoute: typeof AuthenticatedParceirosTerritoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/fornecedores/': {
      id: '/_authenticated/parceiros/fornecedores/'
      path: '/parceiros/fornecedores'
      fullPath: '/parceiros/fornecedores/'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/': {
      id: '/_authenticated/parceiros/financiadores/'
      path: '/parceiros/financiadores'
      fullPath: '/parceiros/financiadores/'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/colaboradores/': {
      id: '/_authenticated/parceiros/colaboradores/'
      path: '/parceiros/colaboradores'
      fullPath: '/parceiros/colaboradores/'
      preLoaderRoute: typeof AuthenticatedParceirosColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/': {
      id: '/_authenticated/parceiros/atos/'
      path: '/parceiros/atos'
      fullPath: '/parceiros/atos/'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/fornecedores/criar': {
      id: '/_authenticated/parceiros/fornecedores/criar'
      path: '/parceiros/fornecedores/criar'
      fullPath: '/parceiros/fornecedores/criar'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/fornecedores/$id': {
      id: '/_authenticated/parceiros/fornecedores/$id'
      path: '/parceiros/fornecedores/$id'
      fullPath: '/parceiros/fornecedores/$id'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/criar': {
      id: '/_authenticated/parceiros/financiadores/criar'
      path: '/parceiros/financiadores/criar'
      fullPath: '/parceiros/financiadores/criar'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/$id': {
      id: '/_authenticated/parceiros/financiadores/$id'
      path: '/parceiros/financiadores/$id'
      fullPath: '/parceiros/financiadores/$id'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/criar': {
      id: '/_authenticated/parceiros/atos/criar'
      path: '/parceiros/atos/criar'
      fullPath: '/parceiros/atos/criar'
      preLoaderRoute: typeof AuthenticatedParceirosAtosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/$id': {
      id: '/_authenticated/parceiros/atos/$id'
      path: '/parceiros/atos/$id'
      fullPath: '/parceiros/atos/$id'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/aditivo/$id': {
      id: '/_authenticated/contratos/aditivo/$id'
      path: '/contratos/aditivo/$id'
      fullPath: '/contratos/aditivo/$id'
      preLoaderRoute: typeof AuthenticatedContratosAditivoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id/editar': {
      id: '/_authenticated/contratos/$id/editar'
      path: '/editar'
      fullPath: '/contratos/$id/editar'
      preLoaderRoute: typeof AuthenticatedContratosIdEditarRouteImport
      parentRoute: typeof AuthenticatedContratosIdRoute
    }
    '/_authenticated/parceiros/fornecedores/$id/editar': {
      id: '/_authenticated/parceiros/fornecedores/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/fornecedores/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosFornecedoresIdRoute
    }
    '/_authenticated/parceiros/financiadores/$id/editar': {
      id: '/_authenticated/parceiros/financiadores/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/financiadores/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosFinanciadoresIdRoute
    }
    '/_authenticated/parceiros/atos/$id/editar': {
      id: '/_authenticated/parceiros/atos/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/atos/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosAtosIdRoute
    }
  }
}

interface AuthenticatedContratosIdRouteChildren {
  AuthenticatedContratosIdEditarRoute: typeof AuthenticatedContratosIdEditarRoute
}

const AuthenticatedContratosIdRouteChildren: AuthenticatedContratosIdRouteChildren =
  {
    AuthenticatedContratosIdEditarRoute: AuthenticatedContratosIdEditarRoute,
  }

const AuthenticatedContratosIdRouteWithChildren =
  AuthenticatedContratosIdRoute._addFileChildren(
    AuthenticatedContratosIdRouteChildren,
  )

interface AuthenticatedParceirosAtosIdRouteChildren {
  AuthenticatedParceirosAtosIdEditarRoute: typeof AuthenticatedParceirosAtosIdEditarRoute
}

const AuthenticatedParceirosAtosIdRouteChildren: AuthenticatedParceirosAtosIdRouteChildren =
  {
    AuthenticatedParceirosAtosIdEditarRoute:
      AuthenticatedParceirosAtosIdEditarRoute,
  }

const AuthenticatedParceirosAtosIdRouteWithChildren =
  AuthenticatedParceirosAtosIdRoute._addFileChildren(
    AuthenticatedParceirosAtosIdRouteChildren,
  )

interface AuthenticatedParceirosFinanciadoresIdRouteChildren {
  AuthenticatedParceirosFinanciadoresIdEditarRoute: typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
}

const AuthenticatedParceirosFinanciadoresIdRouteChildren: AuthenticatedParceirosFinanciadoresIdRouteChildren =
  {
    AuthenticatedParceirosFinanciadoresIdEditarRoute:
      AuthenticatedParceirosFinanciadoresIdEditarRoute,
  }

const AuthenticatedParceirosFinanciadoresIdRouteWithChildren =
  AuthenticatedParceirosFinanciadoresIdRoute._addFileChildren(
    AuthenticatedParceirosFinanciadoresIdRouteChildren,
  )

interface AuthenticatedParceirosFornecedoresIdRouteChildren {
  AuthenticatedParceirosFornecedoresIdEditarRoute: typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}

const AuthenticatedParceirosFornecedoresIdRouteChildren: AuthenticatedParceirosFornecedoresIdRouteChildren =
  {
    AuthenticatedParceirosFornecedoresIdEditarRoute:
      AuthenticatedParceirosFornecedoresIdEditarRoute,
  }

const AuthenticatedParceirosFornecedoresIdRouteWithChildren =
  AuthenticatedParceirosFornecedoresIdRoute._addFileChildren(
    AuthenticatedParceirosFornecedoresIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRouteWithChildren
  AuthenticatedContratosCriarRoute: typeof AuthenticatedContratosCriarRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedContratosAditivoIdRoute: typeof AuthenticatedContratosAditivoIdRoute
  AuthenticatedParceirosAtosIdRoute: typeof AuthenticatedParceirosAtosIdRouteWithChildren
  AuthenticatedParceirosAtosCriarRoute: typeof AuthenticatedParceirosAtosCriarRoute
  AuthenticatedParceirosFinanciadoresIdRoute: typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  AuthenticatedParceirosFinanciadoresCriarRoute: typeof AuthenticatedParceirosFinanciadoresCriarRoute
  AuthenticatedParceirosFornecedoresIdRoute: typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  AuthenticatedParceirosFornecedoresCriarRoute: typeof AuthenticatedParceirosFornecedoresCriarRoute
  AuthenticatedParceirosAtosIndexRoute: typeof AuthenticatedParceirosAtosIndexRoute
  AuthenticatedParceirosColaboradoresIndexRoute: typeof AuthenticatedParceirosColaboradoresIndexRoute
  AuthenticatedParceirosFinanciadoresIndexRoute: typeof AuthenticatedParceirosFinanciadoresIndexRoute
  AuthenticatedParceirosFornecedoresIndexRoute: typeof AuthenticatedParceirosFornecedoresIndexRoute
  AuthenticatedParceirosTerritoriosIndexRoute: typeof AuthenticatedParceirosTerritoriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRouteWithChildren,
  AuthenticatedContratosCriarRoute: AuthenticatedContratosCriarRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedContratosAditivoIdRoute: AuthenticatedContratosAditivoIdRoute,
  AuthenticatedParceirosAtosIdRoute:
    AuthenticatedParceirosAtosIdRouteWithChildren,
  AuthenticatedParceirosAtosCriarRoute: AuthenticatedParceirosAtosCriarRoute,
  AuthenticatedParceirosFinanciadoresIdRoute:
    AuthenticatedParceirosFinanciadoresIdRouteWithChildren,
  AuthenticatedParceirosFinanciadoresCriarRoute:
    AuthenticatedParceirosFinanciadoresCriarRoute,
  AuthenticatedParceirosFornecedoresIdRoute:
    AuthenticatedParceirosFornecedoresIdRouteWithChildren,
  AuthenticatedParceirosFornecedoresCriarRoute:
    AuthenticatedParceirosFornecedoresCriarRoute,
  AuthenticatedParceirosAtosIndexRoute: AuthenticatedParceirosAtosIndexRoute,
  AuthenticatedParceirosColaboradoresIndexRoute:
    AuthenticatedParceirosColaboradoresIndexRoute,
  AuthenticatedParceirosFinanciadoresIndexRoute:
    AuthenticatedParceirosFinanciadoresIndexRoute,
  AuthenticatedParceirosFornecedoresIndexRoute:
    AuthenticatedParceirosFornecedoresIndexRoute,
  AuthenticatedParceirosTerritoriosIndexRoute:
    AuthenticatedParceirosTerritoriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ShowcaseOrganismsRoute: ShowcaseOrganismsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
