/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './../routes/recuperar-senha'
import { Route as ReadyRouteImport } from './../routes/ready'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as HealthRouteImport } from './../routes/health'
import { Route as AutocadastroRouteImport } from './../routes/autocadastro'
import { Route as ActivateRouteImport } from './../routes/activate'
import { Route as AuthenticatedRouteRouteImport } from './../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as ShowcaseOrganismsRouteImport } from './../routes/showcase/organisms'
import { Route as AuthenticatedPlanejamentoRouteImport } from './../routes/_authenticated/planejamento'
import { Route as AuthenticatedDashboardRouteImport } from './../routes/_authenticated/dashboard'
import { Route as AuthenticatedUsuariosIndexRouteImport } from './../routes/_authenticated/usuarios/index'
import { Route as AuthenticatedProgramasIndexRouteImport } from './../routes/_authenticated/programas/index'
import { Route as AuthenticatedMinhaContaIndexRouteImport } from './../routes/_authenticated/minha-conta/index'
import { Route as AuthenticatedContratosIndexRouteImport } from './../routes/_authenticated/contratos/index'
import { Route as AuthenticatedUsuariosCriarRouteImport } from './../routes/_authenticated/usuarios/criar'
import { Route as AuthenticatedUsuariosIdRouteImport } from './../routes/_authenticated/usuarios/$id'
import { Route as AuthenticatedProgramasCriarRouteImport } from './../routes/_authenticated/programas/criar'
import { Route as AuthenticatedProgramasIdRouteImport } from './../routes/_authenticated/programas/$id'
import { Route as AuthenticatedContratosCriarRouteImport } from './../routes/_authenticated/contratos/criar'
import { Route as AuthenticatedContratosIdRouteImport } from './../routes/_authenticated/contratos/$id'
import { Route as AuthenticatedParceirosTerritoriosIndexRouteImport } from './../routes/_authenticated/parceiros/territorios/index'
import { Route as AuthenticatedParceirosFornecedoresIndexRouteImport } from './../routes/_authenticated/parceiros/fornecedores/index'
import { Route as AuthenticatedParceirosFinanciadoresIndexRouteImport } from './../routes/_authenticated/parceiros/financiadores/index'
import { Route as AuthenticatedParceirosColaboradoresIndexRouteImport } from './../routes/_authenticated/parceiros/colaboradores/index'
import { Route as AuthenticatedParceirosAtosIndexRouteImport } from './../routes/_authenticated/parceiros/atos/index'
import { Route as AuthenticatedFinanceiroContasAPagarIndexRouteImport } from './../routes/_authenticated/financeiro/contas-a-pagar/index'
import { Route as AuthenticatedFinanceiroConciliacaoIndexRouteImport } from './../routes/_authenticated/financeiro/conciliacao/index'
import { Route as AuthenticatedPlanejamentoDetalhesIdRouteImport } from './../routes/_authenticated/planejamento.detalhes.$id'
import { Route as AuthenticatedParceirosFornecedoresCriarRouteImport } from './../routes/_authenticated/parceiros/fornecedores/criar'
import { Route as AuthenticatedParceirosFornecedoresIdRouteImport } from './../routes/_authenticated/parceiros/fornecedores/$id'
import { Route as AuthenticatedParceirosFinanciadoresCriarRouteImport } from './../routes/_authenticated/parceiros/financiadores/criar'
import { Route as AuthenticatedParceirosFinanciadoresIdRouteImport } from './../routes/_authenticated/parceiros/financiadores/$id'
import { Route as AuthenticatedParceirosColaboradoresCriarRouteImport } from './../routes/_authenticated/parceiros/colaboradores/criar'
import { Route as AuthenticatedParceirosColaboradoresIdRouteImport } from './../routes/_authenticated/parceiros/colaboradores/$id'
import { Route as AuthenticatedParceirosAtosCriarRouteImport } from './../routes/_authenticated/parceiros/atos/criar'
import { Route as AuthenticatedParceirosAtosIdRouteImport } from './../routes/_authenticated/parceiros/atos/$id'
import { Route as AuthenticatedFinanceiroContasAPagarLancarRouteImport } from './../routes/_authenticated/financeiro/contas-a-pagar/lancar'
import { Route as AuthenticatedFinanceiroConciliacaoAccountIdRouteImport } from './../routes/_authenticated/financeiro/conciliacao/$accountId'
import { Route as AuthenticatedContratosAditivoIdRouteImport } from './../routes/_authenticated/contratos/aditivo.$id'
import { Route as AuthenticatedContratosIdEditarRouteImport } from './../routes/_authenticated/contratos/$id.editar'
import { Route as AuthenticatedParceirosFornecedoresIdEditarRouteImport } from './../routes/_authenticated/parceiros/fornecedores/$id.editar'
import { Route as AuthenticatedParceirosFinanciadoresIdEditarRouteImport } from './../routes/_authenticated/parceiros/financiadores/$id.editar'
import { Route as AuthenticatedParceirosAtosIdEditarRouteImport } from './../routes/_authenticated/parceiros/atos/$id.editar'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AutocadastroRoute = AutocadastroRouteImport.update({
  id: '/autocadastro',
  path: '/autocadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseOrganismsRoute = ShowcaseOrganismsRouteImport.update({
  id: '/showcase/organisms',
  path: '/showcase/organisms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosIndexRoute =
  AuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramasIndexRoute =
  AuthenticatedProgramasIndexRouteImport.update({
    id: '/programas/',
    path: '/programas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaContaIndexRoute =
  AuthenticatedMinhaContaIndexRouteImport.update({
    id: '/minha-conta/',
    path: '/minha-conta/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosCriarRoute =
  AuthenticatedUsuariosCriarRouteImport.update({
    id: '/usuarios/criar',
    path: '/usuarios/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosIdRoute = AuthenticatedUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramasCriarRoute =
  AuthenticatedProgramasCriarRouteImport.update({
    id: '/programas/criar',
    path: '/programas/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgramasIdRoute =
  AuthenticatedProgramasIdRouteImport.update({
    id: '/programas/$id',
    path: '/programas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosCriarRoute =
  AuthenticatedContratosCriarRouteImport.update({
    id: '/contratos/criar',
    path: '/contratos/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosTerritoriosIndexRoute =
  AuthenticatedParceirosTerritoriosIndexRouteImport.update({
    id: '/parceiros/territorios/',
    path: '/parceiros/territorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIndexRoute =
  AuthenticatedParceirosFornecedoresIndexRouteImport.update({
    id: '/parceiros/fornecedores/',
    path: '/parceiros/fornecedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIndexRoute =
  AuthenticatedParceirosFinanciadoresIndexRouteImport.update({
    id: '/parceiros/financiadores/',
    path: '/parceiros/financiadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosColaboradoresIndexRoute =
  AuthenticatedParceirosColaboradoresIndexRouteImport.update({
    id: '/parceiros/colaboradores/',
    path: '/parceiros/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosIndexRoute =
  AuthenticatedParceirosAtosIndexRouteImport.update({
    id: '/parceiros/atos/',
    path: '/parceiros/atos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasAPagarIndexRoute =
  AuthenticatedFinanceiroContasAPagarIndexRouteImport.update({
    id: '/financeiro/contas-a-pagar/',
    path: '/financeiro/contas-a-pagar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoIndexRoute =
  AuthenticatedFinanceiroConciliacaoIndexRouteImport.update({
    id: '/financeiro/conciliacao/',
    path: '/financeiro/conciliacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoDetalhesIdRoute =
  AuthenticatedPlanejamentoDetalhesIdRouteImport.update({
    id: '/detalhes/$id',
    path: '/detalhes/$id',
    getParentRoute: () => AuthenticatedPlanejamentoRoute,
  } as any)
const AuthenticatedParceirosFornecedoresCriarRoute =
  AuthenticatedParceirosFornecedoresCriarRouteImport.update({
    id: '/parceiros/fornecedores/criar',
    path: '/parceiros/fornecedores/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIdRoute =
  AuthenticatedParceirosFornecedoresIdRouteImport.update({
    id: '/parceiros/fornecedores/$id',
    path: '/parceiros/fornecedores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresCriarRoute =
  AuthenticatedParceirosFinanciadoresCriarRouteImport.update({
    id: '/parceiros/financiadores/criar',
    path: '/parceiros/financiadores/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIdRoute =
  AuthenticatedParceirosFinanciadoresIdRouteImport.update({
    id: '/parceiros/financiadores/$id',
    path: '/parceiros/financiadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosColaboradoresCriarRoute =
  AuthenticatedParceirosColaboradoresCriarRouteImport.update({
    id: '/parceiros/colaboradores/criar',
    path: '/parceiros/colaboradores/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosColaboradoresIdRoute =
  AuthenticatedParceirosColaboradoresIdRouteImport.update({
    id: '/parceiros/colaboradores/$id',
    path: '/parceiros/colaboradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosCriarRoute =
  AuthenticatedParceirosAtosCriarRouteImport.update({
    id: '/parceiros/atos/criar',
    path: '/parceiros/atos/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParceirosAtosIdRoute =
  AuthenticatedParceirosAtosIdRouteImport.update({
    id: '/parceiros/atos/$id',
    path: '/parceiros/atos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasAPagarLancarRoute =
  AuthenticatedFinanceiroContasAPagarLancarRouteImport.update({
    id: '/financeiro/contas-a-pagar/lancar',
    path: '/financeiro/contas-a-pagar/lancar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoAccountIdRoute =
  AuthenticatedFinanceiroConciliacaoAccountIdRouteImport.update({
    id: '/financeiro/conciliacao/$accountId',
    path: '/financeiro/conciliacao/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosAditivoIdRoute =
  AuthenticatedContratosAditivoIdRouteImport.update({
    id: '/contratos/aditivo/$id',
    path: '/contratos/aditivo/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdEditarRoute =
  AuthenticatedContratosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedContratosIdRoute,
  } as any)
const AuthenticatedParceirosFornecedoresIdEditarRoute =
  AuthenticatedParceirosFornecedoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosFornecedoresIdRoute,
  } as any)
const AuthenticatedParceirosFinanciadoresIdEditarRoute =
  AuthenticatedParceirosFinanciadoresIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosFinanciadoresIdRoute,
  } as any)
const AuthenticatedParceirosAtosIdEditarRoute =
  AuthenticatedParceirosAtosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedParceirosAtosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/autocadastro': typeof AutocadastroRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRouteWithChildren
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/programas/$id': typeof AuthenticatedProgramasIdRoute
  '/programas/criar': typeof AuthenticatedProgramasCriarRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/usuarios/criar': typeof AuthenticatedUsuariosCriarRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/minha-conta/': typeof AuthenticatedMinhaContaIndexRoute
  '/programas/': typeof AuthenticatedProgramasIndexRoute
  '/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/financeiro/conciliacao/$accountId': typeof AuthenticatedFinanceiroConciliacaoAccountIdRoute
  '/financeiro/contas-a-pagar/lancar': typeof AuthenticatedFinanceiroContasAPagarLancarRoute
  '/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/parceiros/colaboradores/$id': typeof AuthenticatedParceirosColaboradoresIdRoute
  '/parceiros/colaboradores/criar': typeof AuthenticatedParceirosColaboradoresCriarRoute
  '/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/planejamento/detalhes/$id': typeof AuthenticatedPlanejamentoDetalhesIdRoute
  '/financeiro/conciliacao/': typeof AuthenticatedFinanceiroConciliacaoIndexRoute
  '/financeiro/contas-a-pagar/': typeof AuthenticatedFinanceiroContasAPagarIndexRoute
  '/parceiros/atos/': typeof AuthenticatedParceirosAtosIndexRoute
  '/parceiros/colaboradores/': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/parceiros/financiadores/': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/parceiros/fornecedores/': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/parceiros/territorios/': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/autocadastro': typeof AutocadastroRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRouteWithChildren
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/programas/$id': typeof AuthenticatedProgramasIdRoute
  '/programas/criar': typeof AuthenticatedProgramasCriarRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/usuarios/criar': typeof AuthenticatedUsuariosCriarRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/minha-conta': typeof AuthenticatedMinhaContaIndexRoute
  '/programas': typeof AuthenticatedProgramasIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/financeiro/conciliacao/$accountId': typeof AuthenticatedFinanceiroConciliacaoAccountIdRoute
  '/financeiro/contas-a-pagar/lancar': typeof AuthenticatedFinanceiroContasAPagarLancarRoute
  '/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/parceiros/colaboradores/$id': typeof AuthenticatedParceirosColaboradoresIdRoute
  '/parceiros/colaboradores/criar': typeof AuthenticatedParceirosColaboradoresCriarRoute
  '/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/planejamento/detalhes/$id': typeof AuthenticatedPlanejamentoDetalhesIdRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoIndexRoute
  '/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarIndexRoute
  '/parceiros/atos': typeof AuthenticatedParceirosAtosIndexRoute
  '/parceiros/colaboradores': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/parceiros/financiadores': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/parceiros/fornecedores': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/parceiros/territorios': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/autocadastro': typeof AutocadastroRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/ready': typeof ReadyRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRouteWithChildren
  '/showcase/organisms': typeof ShowcaseOrganismsRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/_authenticated/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/_authenticated/programas/$id': typeof AuthenticatedProgramasIdRoute
  '/_authenticated/programas/criar': typeof AuthenticatedProgramasCriarRoute
  '/_authenticated/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/_authenticated/usuarios/criar': typeof AuthenticatedUsuariosCriarRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/minha-conta/': typeof AuthenticatedMinhaContaIndexRoute
  '/_authenticated/programas/': typeof AuthenticatedProgramasIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/_authenticated/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/_authenticated/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
  '/_authenticated/financeiro/conciliacao/$accountId': typeof AuthenticatedFinanceiroConciliacaoAccountIdRoute
  '/_authenticated/financeiro/contas-a-pagar/lancar': typeof AuthenticatedFinanceiroContasAPagarLancarRoute
  '/_authenticated/parceiros/atos/$id': typeof AuthenticatedParceirosAtosIdRouteWithChildren
  '/_authenticated/parceiros/atos/criar': typeof AuthenticatedParceirosAtosCriarRoute
  '/_authenticated/parceiros/colaboradores/$id': typeof AuthenticatedParceirosColaboradoresIdRoute
  '/_authenticated/parceiros/colaboradores/criar': typeof AuthenticatedParceirosColaboradoresCriarRoute
  '/_authenticated/parceiros/financiadores/$id': typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  '/_authenticated/parceiros/financiadores/criar': typeof AuthenticatedParceirosFinanciadoresCriarRoute
  '/_authenticated/parceiros/fornecedores/$id': typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  '/_authenticated/parceiros/fornecedores/criar': typeof AuthenticatedParceirosFornecedoresCriarRoute
  '/_authenticated/planejamento/detalhes/$id': typeof AuthenticatedPlanejamentoDetalhesIdRoute
  '/_authenticated/financeiro/conciliacao/': typeof AuthenticatedFinanceiroConciliacaoIndexRoute
  '/_authenticated/financeiro/contas-a-pagar/': typeof AuthenticatedFinanceiroContasAPagarIndexRoute
  '/_authenticated/parceiros/atos/': typeof AuthenticatedParceirosAtosIndexRoute
  '/_authenticated/parceiros/colaboradores/': typeof AuthenticatedParceirosColaboradoresIndexRoute
  '/_authenticated/parceiros/financiadores/': typeof AuthenticatedParceirosFinanciadoresIndexRoute
  '/_authenticated/parceiros/fornecedores/': typeof AuthenticatedParceirosFornecedoresIndexRoute
  '/_authenticated/parceiros/territorios/': typeof AuthenticatedParceirosTerritoriosIndexRoute
  '/_authenticated/parceiros/atos/$id/editar': typeof AuthenticatedParceirosAtosIdEditarRoute
  '/_authenticated/parceiros/financiadores/$id/editar': typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
  '/_authenticated/parceiros/fornecedores/$id/editar': typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/autocadastro'
    | '/health'
    | '/login'
    | '/ready'
    | '/recuperar-senha'
    | '/reset-password'
    | '/dashboard'
    | '/planejamento'
    | '/showcase/organisms'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/programas/$id'
    | '/programas/criar'
    | '/usuarios/$id'
    | '/usuarios/criar'
    | '/contratos/'
    | '/minha-conta/'
    | '/programas/'
    | '/usuarios/'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
    | '/financeiro/conciliacao/$accountId'
    | '/financeiro/contas-a-pagar/lancar'
    | '/parceiros/atos/$id'
    | '/parceiros/atos/criar'
    | '/parceiros/colaboradores/$id'
    | '/parceiros/colaboradores/criar'
    | '/parceiros/financiadores/$id'
    | '/parceiros/financiadores/criar'
    | '/parceiros/fornecedores/$id'
    | '/parceiros/fornecedores/criar'
    | '/planejamento/detalhes/$id'
    | '/financeiro/conciliacao/'
    | '/financeiro/contas-a-pagar/'
    | '/parceiros/atos/'
    | '/parceiros/colaboradores/'
    | '/parceiros/financiadores/'
    | '/parceiros/fornecedores/'
    | '/parceiros/territorios/'
    | '/parceiros/atos/$id/editar'
    | '/parceiros/financiadores/$id/editar'
    | '/parceiros/fornecedores/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/autocadastro'
    | '/health'
    | '/login'
    | '/ready'
    | '/recuperar-senha'
    | '/reset-password'
    | '/dashboard'
    | '/planejamento'
    | '/showcase/organisms'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/programas/$id'
    | '/programas/criar'
    | '/usuarios/$id'
    | '/usuarios/criar'
    | '/contratos'
    | '/minha-conta'
    | '/programas'
    | '/usuarios'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
    | '/financeiro/conciliacao/$accountId'
    | '/financeiro/contas-a-pagar/lancar'
    | '/parceiros/atos/$id'
    | '/parceiros/atos/criar'
    | '/parceiros/colaboradores/$id'
    | '/parceiros/colaboradores/criar'
    | '/parceiros/financiadores/$id'
    | '/parceiros/financiadores/criar'
    | '/parceiros/fornecedores/$id'
    | '/parceiros/fornecedores/criar'
    | '/planejamento/detalhes/$id'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-a-pagar'
    | '/parceiros/atos'
    | '/parceiros/colaboradores'
    | '/parceiros/financiadores'
    | '/parceiros/fornecedores'
    | '/parceiros/territorios'
    | '/parceiros/atos/$id/editar'
    | '/parceiros/financiadores/$id/editar'
    | '/parceiros/fornecedores/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/autocadastro'
    | '/health'
    | '/login'
    | '/ready'
    | '/recuperar-senha'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/planejamento'
    | '/showcase/organisms'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/criar'
    | '/_authenticated/programas/$id'
    | '/_authenticated/programas/criar'
    | '/_authenticated/usuarios/$id'
    | '/_authenticated/usuarios/criar'
    | '/_authenticated/contratos/'
    | '/_authenticated/minha-conta/'
    | '/_authenticated/programas/'
    | '/_authenticated/usuarios/'
    | '/_authenticated/contratos/$id/editar'
    | '/_authenticated/contratos/aditivo/$id'
    | '/_authenticated/financeiro/conciliacao/$accountId'
    | '/_authenticated/financeiro/contas-a-pagar/lancar'
    | '/_authenticated/parceiros/atos/$id'
    | '/_authenticated/parceiros/atos/criar'
    | '/_authenticated/parceiros/colaboradores/$id'
    | '/_authenticated/parceiros/colaboradores/criar'
    | '/_authenticated/parceiros/financiadores/$id'
    | '/_authenticated/parceiros/financiadores/criar'
    | '/_authenticated/parceiros/fornecedores/$id'
    | '/_authenticated/parceiros/fornecedores/criar'
    | '/_authenticated/planejamento/detalhes/$id'
    | '/_authenticated/financeiro/conciliacao/'
    | '/_authenticated/financeiro/contas-a-pagar/'
    | '/_authenticated/parceiros/atos/'
    | '/_authenticated/parceiros/colaboradores/'
    | '/_authenticated/parceiros/financiadores/'
    | '/_authenticated/parceiros/fornecedores/'
    | '/_authenticated/parceiros/territorios/'
    | '/_authenticated/parceiros/atos/$id/editar'
    | '/_authenticated/parceiros/financiadores/$id/editar'
    | '/_authenticated/parceiros/fornecedores/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AutocadastroRoute: typeof AutocadastroRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ReadyRoute: typeof ReadyRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShowcaseOrganismsRoute: typeof ShowcaseOrganismsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocadastro': {
      id: '/autocadastro'
      path: '/autocadastro'
      fullPath: '/autocadastro'
      preLoaderRoute: typeof AutocadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/organisms': {
      id: '/showcase/organisms'
      path: '/showcase/organisms'
      fullPath: '/showcase/organisms'
      preLoaderRoute: typeof ShowcaseOrganismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programas/': {
      id: '/_authenticated/programas/'
      path: '/programas'
      fullPath: '/programas/'
      preLoaderRoute: typeof AuthenticatedProgramasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta/': {
      id: '/_authenticated/minha-conta/'
      path: '/minha-conta'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof AuthenticatedMinhaContaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios/criar': {
      id: '/_authenticated/usuarios/criar'
      path: '/usuarios/criar'
      fullPath: '/usuarios/criar'
      preLoaderRoute: typeof AuthenticatedUsuariosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios/$id': {
      id: '/_authenticated/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programas/criar': {
      id: '/_authenticated/programas/criar'
      path: '/programas/criar'
      fullPath: '/programas/criar'
      preLoaderRoute: typeof AuthenticatedProgramasCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programas/$id': {
      id: '/_authenticated/programas/$id'
      path: '/programas/$id'
      fullPath: '/programas/$id'
      preLoaderRoute: typeof AuthenticatedProgramasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/criar': {
      id: '/_authenticated/contratos/criar'
      path: '/contratos/criar'
      fullPath: '/contratos/criar'
      preLoaderRoute: typeof AuthenticatedContratosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/territorios/': {
      id: '/_authenticated/parceiros/territorios/'
      path: '/parceiros/territorios'
      fullPath: '/parceiros/territorios/'
      preLoaderRoute: typeof AuthenticatedParceirosTerritoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/fornecedores/': {
      id: '/_authenticated/parceiros/fornecedores/'
      path: '/parceiros/fornecedores'
      fullPath: '/parceiros/fornecedores/'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/': {
      id: '/_authenticated/parceiros/financiadores/'
      path: '/parceiros/financiadores'
      fullPath: '/parceiros/financiadores/'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/colaboradores/': {
      id: '/_authenticated/parceiros/colaboradores/'
      path: '/parceiros/colaboradores'
      fullPath: '/parceiros/colaboradores/'
      preLoaderRoute: typeof AuthenticatedParceirosColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/': {
      id: '/_authenticated/parceiros/atos/'
      path: '/parceiros/atos'
      fullPath: '/parceiros/atos/'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-a-pagar/': {
      id: '/_authenticated/financeiro/contas-a-pagar/'
      path: '/financeiro/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar/'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAPagarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao/': {
      id: '/_authenticated/financeiro/conciliacao/'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao/'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento/detalhes/$id': {
      id: '/_authenticated/planejamento/detalhes/$id'
      path: '/detalhes/$id'
      fullPath: '/planejamento/detalhes/$id'
      preLoaderRoute: typeof AuthenticatedPlanejamentoDetalhesIdRouteImport
      parentRoute: typeof AuthenticatedPlanejamentoRoute
    }
    '/_authenticated/parceiros/fornecedores/criar': {
      id: '/_authenticated/parceiros/fornecedores/criar'
      path: '/parceiros/fornecedores/criar'
      fullPath: '/parceiros/fornecedores/criar'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/fornecedores/$id': {
      id: '/_authenticated/parceiros/fornecedores/$id'
      path: '/parceiros/fornecedores/$id'
      fullPath: '/parceiros/fornecedores/$id'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/criar': {
      id: '/_authenticated/parceiros/financiadores/criar'
      path: '/parceiros/financiadores/criar'
      fullPath: '/parceiros/financiadores/criar'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/financiadores/$id': {
      id: '/_authenticated/parceiros/financiadores/$id'
      path: '/parceiros/financiadores/$id'
      fullPath: '/parceiros/financiadores/$id'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/colaboradores/criar': {
      id: '/_authenticated/parceiros/colaboradores/criar'
      path: '/parceiros/colaboradores/criar'
      fullPath: '/parceiros/colaboradores/criar'
      preLoaderRoute: typeof AuthenticatedParceirosColaboradoresCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/colaboradores/$id': {
      id: '/_authenticated/parceiros/colaboradores/$id'
      path: '/parceiros/colaboradores/$id'
      fullPath: '/parceiros/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedParceirosColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/criar': {
      id: '/_authenticated/parceiros/atos/criar'
      path: '/parceiros/atos/criar'
      fullPath: '/parceiros/atos/criar'
      preLoaderRoute: typeof AuthenticatedParceirosAtosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiros/atos/$id': {
      id: '/_authenticated/parceiros/atos/$id'
      path: '/parceiros/atos/$id'
      fullPath: '/parceiros/atos/$id'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-a-pagar/lancar': {
      id: '/_authenticated/financeiro/contas-a-pagar/lancar'
      path: '/financeiro/contas-a-pagar/lancar'
      fullPath: '/financeiro/contas-a-pagar/lancar'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAPagarLancarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao/$accountId': {
      id: '/_authenticated/financeiro/conciliacao/$accountId'
      path: '/financeiro/conciliacao/$accountId'
      fullPath: '/financeiro/conciliacao/$accountId'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/aditivo/$id': {
      id: '/_authenticated/contratos/aditivo/$id'
      path: '/contratos/aditivo/$id'
      fullPath: '/contratos/aditivo/$id'
      preLoaderRoute: typeof AuthenticatedContratosAditivoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id/editar': {
      id: '/_authenticated/contratos/$id/editar'
      path: '/editar'
      fullPath: '/contratos/$id/editar'
      preLoaderRoute: typeof AuthenticatedContratosIdEditarRouteImport
      parentRoute: typeof AuthenticatedContratosIdRoute
    }
    '/_authenticated/parceiros/fornecedores/$id/editar': {
      id: '/_authenticated/parceiros/fornecedores/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/fornecedores/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosFornecedoresIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosFornecedoresIdRoute
    }
    '/_authenticated/parceiros/financiadores/$id/editar': {
      id: '/_authenticated/parceiros/financiadores/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/financiadores/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosFinanciadoresIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosFinanciadoresIdRoute
    }
    '/_authenticated/parceiros/atos/$id/editar': {
      id: '/_authenticated/parceiros/atos/$id/editar'
      path: '/editar'
      fullPath: '/parceiros/atos/$id/editar'
      preLoaderRoute: typeof AuthenticatedParceirosAtosIdEditarRouteImport
      parentRoute: typeof AuthenticatedParceirosAtosIdRoute
    }
  }
}

interface AuthenticatedPlanejamentoRouteChildren {
  AuthenticatedPlanejamentoDetalhesIdRoute: typeof AuthenticatedPlanejamentoDetalhesIdRoute
}

const AuthenticatedPlanejamentoRouteChildren: AuthenticatedPlanejamentoRouteChildren =
  {
    AuthenticatedPlanejamentoDetalhesIdRoute:
      AuthenticatedPlanejamentoDetalhesIdRoute,
  }

const AuthenticatedPlanejamentoRouteWithChildren =
  AuthenticatedPlanejamentoRoute._addFileChildren(
    AuthenticatedPlanejamentoRouteChildren,
  )

interface AuthenticatedContratosIdRouteChildren {
  AuthenticatedContratosIdEditarRoute: typeof AuthenticatedContratosIdEditarRoute
}

const AuthenticatedContratosIdRouteChildren: AuthenticatedContratosIdRouteChildren =
  {
    AuthenticatedContratosIdEditarRoute: AuthenticatedContratosIdEditarRoute,
  }

const AuthenticatedContratosIdRouteWithChildren =
  AuthenticatedContratosIdRoute._addFileChildren(
    AuthenticatedContratosIdRouteChildren,
  )

interface AuthenticatedParceirosAtosIdRouteChildren {
  AuthenticatedParceirosAtosIdEditarRoute: typeof AuthenticatedParceirosAtosIdEditarRoute
}

const AuthenticatedParceirosAtosIdRouteChildren: AuthenticatedParceirosAtosIdRouteChildren =
  {
    AuthenticatedParceirosAtosIdEditarRoute:
      AuthenticatedParceirosAtosIdEditarRoute,
  }

const AuthenticatedParceirosAtosIdRouteWithChildren =
  AuthenticatedParceirosAtosIdRoute._addFileChildren(
    AuthenticatedParceirosAtosIdRouteChildren,
  )

interface AuthenticatedParceirosFinanciadoresIdRouteChildren {
  AuthenticatedParceirosFinanciadoresIdEditarRoute: typeof AuthenticatedParceirosFinanciadoresIdEditarRoute
}

const AuthenticatedParceirosFinanciadoresIdRouteChildren: AuthenticatedParceirosFinanciadoresIdRouteChildren =
  {
    AuthenticatedParceirosFinanciadoresIdEditarRoute:
      AuthenticatedParceirosFinanciadoresIdEditarRoute,
  }

const AuthenticatedParceirosFinanciadoresIdRouteWithChildren =
  AuthenticatedParceirosFinanciadoresIdRoute._addFileChildren(
    AuthenticatedParceirosFinanciadoresIdRouteChildren,
  )

interface AuthenticatedParceirosFornecedoresIdRouteChildren {
  AuthenticatedParceirosFornecedoresIdEditarRoute: typeof AuthenticatedParceirosFornecedoresIdEditarRoute
}

const AuthenticatedParceirosFornecedoresIdRouteChildren: AuthenticatedParceirosFornecedoresIdRouteChildren =
  {
    AuthenticatedParceirosFornecedoresIdEditarRoute:
      AuthenticatedParceirosFornecedoresIdEditarRoute,
  }

const AuthenticatedParceirosFornecedoresIdRouteWithChildren =
  AuthenticatedParceirosFornecedoresIdRoute._addFileChildren(
    AuthenticatedParceirosFornecedoresIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRouteWithChildren
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRouteWithChildren
  AuthenticatedContratosCriarRoute: typeof AuthenticatedContratosCriarRoute
  AuthenticatedProgramasIdRoute: typeof AuthenticatedProgramasIdRoute
  AuthenticatedProgramasCriarRoute: typeof AuthenticatedProgramasCriarRoute
  AuthenticatedUsuariosIdRoute: typeof AuthenticatedUsuariosIdRoute
  AuthenticatedUsuariosCriarRoute: typeof AuthenticatedUsuariosCriarRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedMinhaContaIndexRoute: typeof AuthenticatedMinhaContaIndexRoute
  AuthenticatedProgramasIndexRoute: typeof AuthenticatedProgramasIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
  AuthenticatedContratosAditivoIdRoute: typeof AuthenticatedContratosAditivoIdRoute
  AuthenticatedFinanceiroConciliacaoAccountIdRoute: typeof AuthenticatedFinanceiroConciliacaoAccountIdRoute
  AuthenticatedFinanceiroContasAPagarLancarRoute: typeof AuthenticatedFinanceiroContasAPagarLancarRoute
  AuthenticatedParceirosAtosIdRoute: typeof AuthenticatedParceirosAtosIdRouteWithChildren
  AuthenticatedParceirosAtosCriarRoute: typeof AuthenticatedParceirosAtosCriarRoute
  AuthenticatedParceirosColaboradoresIdRoute: typeof AuthenticatedParceirosColaboradoresIdRoute
  AuthenticatedParceirosColaboradoresCriarRoute: typeof AuthenticatedParceirosColaboradoresCriarRoute
  AuthenticatedParceirosFinanciadoresIdRoute: typeof AuthenticatedParceirosFinanciadoresIdRouteWithChildren
  AuthenticatedParceirosFinanciadoresCriarRoute: typeof AuthenticatedParceirosFinanciadoresCriarRoute
  AuthenticatedParceirosFornecedoresIdRoute: typeof AuthenticatedParceirosFornecedoresIdRouteWithChildren
  AuthenticatedParceirosFornecedoresCriarRoute: typeof AuthenticatedParceirosFornecedoresCriarRoute
  AuthenticatedFinanceiroConciliacaoIndexRoute: typeof AuthenticatedFinanceiroConciliacaoIndexRoute
  AuthenticatedFinanceiroContasAPagarIndexRoute: typeof AuthenticatedFinanceiroContasAPagarIndexRoute
  AuthenticatedParceirosAtosIndexRoute: typeof AuthenticatedParceirosAtosIndexRoute
  AuthenticatedParceirosColaboradoresIndexRoute: typeof AuthenticatedParceirosColaboradoresIndexRoute
  AuthenticatedParceirosFinanciadoresIndexRoute: typeof AuthenticatedParceirosFinanciadoresIndexRoute
  AuthenticatedParceirosFornecedoresIndexRoute: typeof AuthenticatedParceirosFornecedoresIndexRoute
  AuthenticatedParceirosTerritoriosIndexRoute: typeof AuthenticatedParceirosTerritoriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRouteWithChildren,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRouteWithChildren,
  AuthenticatedContratosCriarRoute: AuthenticatedContratosCriarRoute,
  AuthenticatedProgramasIdRoute: AuthenticatedProgramasIdRoute,
  AuthenticatedProgramasCriarRoute: AuthenticatedProgramasCriarRoute,
  AuthenticatedUsuariosIdRoute: AuthenticatedUsuariosIdRoute,
  AuthenticatedUsuariosCriarRoute: AuthenticatedUsuariosCriarRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedMinhaContaIndexRoute: AuthenticatedMinhaContaIndexRoute,
  AuthenticatedProgramasIndexRoute: AuthenticatedProgramasIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
  AuthenticatedContratosAditivoIdRoute: AuthenticatedContratosAditivoIdRoute,
  AuthenticatedFinanceiroConciliacaoAccountIdRoute:
    AuthenticatedFinanceiroConciliacaoAccountIdRoute,
  AuthenticatedFinanceiroContasAPagarLancarRoute:
    AuthenticatedFinanceiroContasAPagarLancarRoute,
  AuthenticatedParceirosAtosIdRoute:
    AuthenticatedParceirosAtosIdRouteWithChildren,
  AuthenticatedParceirosAtosCriarRoute: AuthenticatedParceirosAtosCriarRoute,
  AuthenticatedParceirosColaboradoresIdRoute:
    AuthenticatedParceirosColaboradoresIdRoute,
  AuthenticatedParceirosColaboradoresCriarRoute:
    AuthenticatedParceirosColaboradoresCriarRoute,
  AuthenticatedParceirosFinanciadoresIdRoute:
    AuthenticatedParceirosFinanciadoresIdRouteWithChildren,
  AuthenticatedParceirosFinanciadoresCriarRoute:
    AuthenticatedParceirosFinanciadoresCriarRoute,
  AuthenticatedParceirosFornecedoresIdRoute:
    AuthenticatedParceirosFornecedoresIdRouteWithChildren,
  AuthenticatedParceirosFornecedoresCriarRoute:
    AuthenticatedParceirosFornecedoresCriarRoute,
  AuthenticatedFinanceiroConciliacaoIndexRoute:
    AuthenticatedFinanceiroConciliacaoIndexRoute,
  AuthenticatedFinanceiroContasAPagarIndexRoute:
    AuthenticatedFinanceiroContasAPagarIndexRoute,
  AuthenticatedParceirosAtosIndexRoute: AuthenticatedParceirosAtosIndexRoute,
  AuthenticatedParceirosColaboradoresIndexRoute:
    AuthenticatedParceirosColaboradoresIndexRoute,
  AuthenticatedParceirosFinanciadoresIndexRoute:
    AuthenticatedParceirosFinanciadoresIndexRoute,
  AuthenticatedParceirosFornecedoresIndexRoute:
    AuthenticatedParceirosFornecedoresIndexRoute,
  AuthenticatedParceirosTerritoriosIndexRoute:
    AuthenticatedParceirosTerritoriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AutocadastroRoute: AutocadastroRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ReadyRoute: ReadyRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShowcaseOrganismsRoute: ShowcaseOrganismsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
