/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos/index'
import { Route as AuthenticatedContratosAdicionarRouteImport } from './routes/_authenticated/contratos/adicionar'
import { Route as AuthenticatedContratosEditarIdRouteImport } from './routes/_authenticated/contratos/editar.$id'
import { Route as AuthenticatedContratosDetalhesIdRouteImport } from './routes/_authenticated/contratos/detalhes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosAdicionarRoute =
  AuthenticatedContratosAdicionarRouteImport.update({
    id: '/contratos/adicionar',
    path: '/contratos/adicionar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosEditarIdRoute =
  AuthenticatedContratosEditarIdRouteImport.update({
    id: '/contratos/editar/$id',
    path: '/contratos/editar/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosDetalhesIdRoute =
  AuthenticatedContratosDetalhesIdRouteImport.update({
    id: '/contratos/detalhes/$id',
    path: '/contratos/detalhes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/contratos/adicionar': typeof AuthenticatedContratosAdicionarRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/contratos/detalhes/$id': typeof AuthenticatedContratosDetalhesIdRoute
  '/contratos/editar/$id': typeof AuthenticatedContratosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/contratos/adicionar': typeof AuthenticatedContratosAdicionarRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/contratos/detalhes/$id': typeof AuthenticatedContratosDetalhesIdRoute
  '/contratos/editar/$id': typeof AuthenticatedContratosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/contratos/adicionar': typeof AuthenticatedContratosAdicionarRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/contratos/detalhes/$id': typeof AuthenticatedContratosDetalhesIdRoute
  '/_authenticated/contratos/editar/$id': typeof AuthenticatedContratosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contratos/adicionar'
    | '/contratos/'
    | '/contratos/detalhes/$id'
    | '/contratos/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contratos/adicionar'
    | '/contratos'
    | '/contratos/detalhes/$id'
    | '/contratos/editar/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/contratos/adicionar'
    | '/_authenticated/contratos/'
    | '/_authenticated/contratos/detalhes/$id'
    | '/_authenticated/contratos/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/adicionar': {
      id: '/_authenticated/contratos/adicionar'
      path: '/contratos/adicionar'
      fullPath: '/contratos/adicionar'
      preLoaderRoute: typeof AuthenticatedContratosAdicionarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/editar/$id': {
      id: '/_authenticated/contratos/editar/$id'
      path: '/contratos/editar/$id'
      fullPath: '/contratos/editar/$id'
      preLoaderRoute: typeof AuthenticatedContratosEditarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/detalhes/$id': {
      id: '/_authenticated/contratos/detalhes/$id'
      path: '/contratos/detalhes/$id'
      fullPath: '/contratos/detalhes/$id'
      preLoaderRoute: typeof AuthenticatedContratosDetalhesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContratosAdicionarRoute: typeof AuthenticatedContratosAdicionarRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedContratosDetalhesIdRoute: typeof AuthenticatedContratosDetalhesIdRoute
  AuthenticatedContratosEditarIdRoute: typeof AuthenticatedContratosEditarIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContratosAdicionarRoute: AuthenticatedContratosAdicionarRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedContratosDetalhesIdRoute: AuthenticatedContratosDetalhesIdRoute,
  AuthenticatedContratosEditarIdRoute: AuthenticatedContratosEditarIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
