/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos/index'
import { Route as AuthenticatedContratosCriarRouteImport } from './routes/_authenticated/contratos/criar'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos/$id'
import { Route as AuthenticatedContratosAditivoIdRouteImport } from './routes/_authenticated/contratos/aditivo.$id'
import { Route as AuthenticatedContratosIdEditarRouteImport } from './routes/_authenticated/contratos/$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosCriarRoute =
  AuthenticatedContratosCriarRouteImport.update({
    id: '/contratos/criar',
    path: '/contratos/criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/contratos/$id',
    path: '/contratos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosAditivoIdRoute =
  AuthenticatedContratosAditivoIdRouteImport.update({
    id: '/contratos/aditivo/$id',
    path: '/contratos/aditivo/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIdEditarRoute =
  AuthenticatedContratosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedContratosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/_authenticated/contratos/criar': typeof AuthenticatedContratosCriarRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/contratos/$id/editar': typeof AuthenticatedContratosIdEditarRoute
  '/_authenticated/contratos/aditivo/$id': typeof AuthenticatedContratosAditivoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/dashboard'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/contratos/'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/dashboard'
    | '/contratos/$id'
    | '/contratos/criar'
    | '/contratos'
    | '/contratos/$id/editar'
    | '/contratos/aditivo/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/criar'
    | '/_authenticated/contratos/'
    | '/_authenticated/contratos/$id/editar'
    | '/_authenticated/contratos/aditivo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/criar': {
      id: '/_authenticated/contratos/criar'
      path: '/contratos/criar'
      fullPath: '/contratos/criar'
      preLoaderRoute: typeof AuthenticatedContratosCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/aditivo/$id': {
      id: '/_authenticated/contratos/aditivo/$id'
      path: '/contratos/aditivo/$id'
      fullPath: '/contratos/aditivo/$id'
      preLoaderRoute: typeof AuthenticatedContratosAditivoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$id/editar': {
      id: '/_authenticated/contratos/$id/editar'
      path: '/editar'
      fullPath: '/contratos/$id/editar'
      preLoaderRoute: typeof AuthenticatedContratosIdEditarRouteImport
      parentRoute: typeof AuthenticatedContratosIdRoute
    }
  }
}

interface AuthenticatedContratosIdRouteChildren {
  AuthenticatedContratosIdEditarRoute: typeof AuthenticatedContratosIdEditarRoute
}

const AuthenticatedContratosIdRouteChildren: AuthenticatedContratosIdRouteChildren =
  {
    AuthenticatedContratosIdEditarRoute: AuthenticatedContratosIdEditarRoute,
  }

const AuthenticatedContratosIdRouteWithChildren =
  AuthenticatedContratosIdRoute._addFileChildren(
    AuthenticatedContratosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRouteWithChildren
  AuthenticatedContratosCriarRoute: typeof AuthenticatedContratosCriarRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedContratosAditivoIdRoute: typeof AuthenticatedContratosAditivoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedContratosIdRoute: AuthenticatedContratosIdRouteWithChildren,
  AuthenticatedContratosCriarRoute: AuthenticatedContratosCriarRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedContratosAditivoIdRoute: AuthenticatedContratosAditivoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
